//
//***P1***
//

//deaths

setDeathEvent           P1,CLASS_Fighter,damage,DestDamageSmall.ebg
setDeathEvent           P1,CLASS_Fighter,projectile,DestBeam.ebg
setDeathEvent           P1,CLASS_Fighter,beam,destdamagefighter.ebg
//setDeathEvent           P1,CLASS_Fighter,collision,
//setDeathEvent           P1,CLASS_Fighter,special,

setDeathEvent           P1,CLASS_Corvette,damage,DestDamageSmall.ebg
setDeathEvent           P1,CLASS_Corvette,projectile,destdamagefighter.ebg
setDeathEvent           P1,CLASS_Corvette,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_Corvette,collision,
//setDeathEvent           P1,CLASS_Corvette,special,

setDeathEvent           P1,CLASS_Frigate,damage,DestBeam.ebg
setDeathEvent           P1,CLASS_Frigate,projectile,destdamagefighter.ebg
setDeathEvent           P1,CLASS_Frigate,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_Frigate,collision,
//setDeathEvent           P1,CLASS_Frigate,special,

setDeathEvent           P1,CLASS_Destroyer,damage,DestDamageLarge.ebg
setDeathEvent           P1,CLASS_Destroyer,projectile,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_Destroyer,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_Destroyer,collision,
//setDeathEvent           P1,CLASS_Destroyer,special,

setDeathEvent           P1,CLASS_Carrier,damage,DestDamageLarge.ebg
setDeathEvent           P1,CLASS_Carrier,projectile,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_Carrier,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_Carrier,collision,
//setDeathEvent           P1,CLASS_Carrier,special,

setDeathEvent           P1,CLASS_HeavyCruiser,damage,DestDamageLarge.ebg
setDeathEvent           P1,CLASS_HeavyCruiser,projectile,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_HeavyCruiser,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_HeavyCruiser,collision,
//setDeathEvent           P1,CLASS_HeavyCruiser,special,

setDeathEvent           P1,CLASS_Mothership,damage,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_Mothership,projectile,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_Mothership,beam,B5TestExplosionLarge.ebg
//setDeathEvent           P1,CLASS_Mothership,collision,
//setDeathEvent           P1,CLASS_Mothership,special,

setDeathEvent           P1,CLASS_Resource,damage,DestDamageLarge.ebg
setDeathEvent           P1,CLASS_Resource,projectile,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_Resource,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_Resource,collision,
//setDeathEvent           P1,CLASS_Resource,special,

setDeathEvent           P1,CLASS_NonCombat,damage,DestDamageLarge.ebg
setDeathEvent           P1,CLASS_NonCombat,projectile,B5TestExplosionLarge.ebg
setDeathEvent           P1,CLASS_NonCombat,beam,DestBeam.ebg
//setDeathEvent           P1,CLASS_NonCombat,collision,
//setDeathEvent           P1,CLASS_NonCombat,special,


//firing

setFireEvent            P1,GS_VeryLargeIonCannon,FireIonCannonVeryLarge.ebg
    setFireEvent            P1,GS_VeryLargeIonCannon,FireIonCannonVeryLarge01.ebg
    setFireEvent            P1,GS_VeryLargeIonCannon,FireIonCannonVeryLarge02.ebg
    setFireEvent            P1,GS_VeryLargeIonCannon,FireIonCannonVeryLarge03.ebg
setFireEvent            P1,GS_LargeIonCannon,FireIonCannonLarge.ebg
    setFireEvent            P1,GS_LargeIonCannon,FireIonCannonLarge01.ebg
    setFireEvent            P1,GS_LargeIonCannon,FireIonCannonLarge02.ebg
    setFireEvent            P1,GS_LargeIonCannon,FireIonCannonLarge03.ebg
setFireEvent            P1,GS_MediumIonCannon,FireIonCannonMedium.ebg
    setFireEvent            P1,GS_MediumIonCannon,FireIonCannonMedium01.ebg
    setFireEvent            P1,GS_MediumIonCannon,FireIonCannonMedium02.ebg
    setFireEvent            P1,GS_MediumIonCannon,FireIonCannonMedium03.ebg
setFireEvent            P1,GS_SmallIonCannon,FireIonCannonSmall.ebg
    setFireEvent            P1,GS_SmallIonCannon,FireIonCannonSmall01.ebg
    setFireEvent            P1,GS_SmallIonCannon,FireIonCannonSmall02.ebg
    setFireEvent            P1,GS_SmallIonCannon,FireIonCannonSmall03.ebg

setFireEvent            P1,GS_MediumProjectile,FireProjectileMedium.ebg
    setFireEvent            P1,GS_MediumProjectile,FireProjectileMedium01.ebg
    setFireEvent            P1,GS_MediumProjectile,FireProjectileMedium02.ebg
    setFireEvent            P1,GS_MediumProjectile,FireProjectileMedium03.ebg
setFireEvent            P1,GS_SmallProjectile,FireEnergy.ebg


setFireEvent            P1,GS_VeryLargeEnergyCannon,FireEnergyVeryLarge.ebg
    setFireEvent            P1,GS_VeryLargeEnergyCannon,FireEnergyVeryLarge01.ebg
    setFireEvent            P1,GS_VeryLargeEnergyCannon,FireEnergyVeryLarge02.ebg
    setFireEvent            P1,GS_VeryLargeEnergyCannon,FireEnergyVeryLarge03.ebg
setFireEvent            P1,GS_LargeEnergyCannon,FireEnergyLarge.ebg
    setFireEvent            P1,GS_LargeEnergyCannon,FireEnergyLarge01.ebg
    setFireEvent            P1,GS_LargeEnergyCannon,FireEnergyLarge02.ebg
    setFireEvent            P1,GS_LargeEnergyCannon,FireEnergyLarge03.ebg
setFireEvent            P1,GS_MediumEnergyCannon,FireEnergyMedium.ebg
    setFireEvent            P1,GS_MediumEnergyCannon,FireEnergyMedium01.ebg
    setFireEvent            P1,GS_MediumEnergyCannon,FireEnergyMedium02.ebg
    setFireEvent            P1,GS_MediumEnergyCannon,FireEnergyMedium03.ebg
setFireEvent            P1,GS_SmallEnergyCannon,FireEnergySmall.ebg
    setFireEvent            P1,GS_SmallEnergyCannon,FireEnergySmall01.ebg
    setFireEvent            P1,GS_SmallEnergyCannon,FireEnergySmall02.ebg
    setFireEvent            P1,GS_SmallEnergyCannon,FireEnergySmall03.ebg

setFireEvent            P1,GS_MineLauncher,FireMines.ebg
    setFireEvent            P1,GS_MineLauncher,FireMines01.ebg
    setFireEvent            P1,GS_MineLauncher,FireMines02.ebg
    setFireEvent            P1,GS_MineLauncher,FireMines03.ebg
setFireEvent            P1,GS_MissleLauncher,FireMissiles.ebg
    setFireEvent            P1,GS_MissleLauncher,FireMissiles01.ebg
    setFireEvent            P1,GS_MissleLauncher,FireMissiles02.ebg
    setFireEvent            P1,GS_MissleLauncher,FireMissiles03.ebg
setFireEvent            P1,GS_MediumPlasmaBomb,FirePlasmaMedium.ebg
    setFireEvent            P1,GS_MediumPlasmaBomb,FirePlasmaMedium01.ebg
    setFireEvent            P1,GS_MediumPlasmaBomb,FirePlasmaMedium02.ebg
    setFireEvent            P1,GS_MediumPlasmaBomb,FirePlasmaMedium03.ebg
setFireEvent            P1,GS_VeryLargePlasmaBomb,FireEnergy.ebg
setFireEvent            P1,GS_SmallPlasmaBomb,FirePlasmaSmall.ebg
    setFireEvent            P1,GS_SmallPlasmaBomb,FirePlasmaSmall01.ebg
    setFireEvent            P1,GS_SmallPlasmaBomb,FirePlasmaSmall02.ebg
    setFireEvent            P1,GS_SmallPlasmaBomb,FirePlasmaSmall03.ebg


//hits

setHitEvent             P1,GS_VeryLargeIonCannon,HitExplosive.ebg
    setHitEvent             P1,GS_VeryLargeIonCannon,HitExplosive.ebg
    setHitEvent             P1,GS_VeryLargeIonCannon,HitExplosive.ebg
    setHitEvent             P1,GS_VeryLargeIonCannon,HitExplosive.ebg
setHitEvent             P1,GS_LargeIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_LargeIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_LargeIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_LargeIonCannon,HitIonBeam.ebg
setHitEvent             P1,GS_MediumIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_MediumIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_MediumIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_MediumIonCannon,HitIonBeam.ebg
setHitEvent             P1,GS_SmallIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_SmallIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_SmallIonCannon,HitIonBeam.ebg
    setHitEvent             P1,GS_SmallIonCannon,HitIonBeam.ebg

setHitEvent             P1,GS_MediumProjectile,HitCannon.ebg
    setHitEvent             P1,GS_MediumProjectile,HitCannon.ebg
    setHitEvent             P1,GS_MediumProjectile,HitCannon.ebg
    setHitEvent             P1,GS_MediumProjectile,HitCannon.ebg
setHitEvent             P1,GS_SmallProjectile,HitCannon.ebg
    setHitEvent             P1,GS_SmallProjectile,HitCannon.ebg
    setHitEvent             P1,GS_SmallProjectile,HitCannon.ebg
    setHitEvent             P1,GS_SmallProjectile,HitCannon.ebg

setHitEvent             P1,GS_VeryLargeEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_VeryLargeEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_VeryLargeEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_VeryLargeEnergyCannon,HitCannon.ebg
setHitEvent             P1,GS_LargeEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_LargeEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_LargeEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_LargeEnergyCannon,HitCannon.ebg
setHitEvent             P1,GS_MediumEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_MediumEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_MediumEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_MediumEnergyCannon,HitCannon.ebg
setHitEvent             P1,GS_SmallEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_SmallEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_SmallEnergyCannon,HitCannon.ebg
    setHitEvent             P1,GS_SmallEnergyCannon,HitCannon.ebg

setHitEvent             P1,GS_MineLauncher,HitMines.ebg
    setHitEvent             P1,GS_MineLauncher,HitMines.ebg
    setHitEvent             P1,GS_MineLauncher,HitMines.ebg
    setHitEvent             P1,GS_MineLauncher,HitMines.ebg
setHitEvent             P1,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             P1,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             P1,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             P1,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             P1,GS_MissleLauncher,HitLargeMissile.ebg
setHitEvent             P1,GS_MediumPlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_MediumPlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_MediumPlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_MediumPlasmaBomb,HitMines.ebg
setHitEvent             P1,GS_VeryLargePlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_VeryLargePlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_VeryLargePlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_VeryLargePlasmaBomb,HitMines.ebg
setHitEvent             P1,GS_SmallPlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_SmallPlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_SmallPlasmaBomb,HitMines.ebg
    setHitEvent             P1,GS_SmallPlasmaBomb,HitMines.ebg


setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
setBulletEffect         P1,GS_MediumPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
setBulletEffect         P1,GS_LargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
setBulletEffect         P1,GS_VeryLargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         P1,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg

setBulletEffect         P1,GS_VeryLargeIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_VeryLargeIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_VeryLargeIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_VeryLargeIonCannon,BulletIonRay.ebg
setBulletEffect         P1,GS_LargeIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_LargeIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_LargeIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_LargeIonCannon,BulletIonRay.ebg
setBulletEffect         P1,GS_MediumIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_MediumIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_MediumIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_MediumIonCannon,BulletIonRay.ebg
setBulletEffect         P1,GS_SmallIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_SmallIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_SmallIonCannon,BulletIonRay.ebg
    setBulletEffect         P1,GS_SmallIonCannon,BulletIonRay.ebg

//setBulletEffect         P1,GS_SmallEnergyCannon,BulletEnergy.ebg


setBulletEffect         P1,GS_VeryLargeEnergyCannon,BulletCannonVeryLarge.ebg
    setBulletEffect         P1,GS_VeryLargeEnergyCannon,BulletCannonVeryLarge.ebg
    setBulletEffect         P1,GS_VeryLargeEnergyCannon,BulletCannonVeryLarge02.ebg
    setBulletEffect         P1,GS_VeryLargeEnergyCannon,BulletCannonVeryLarge03.ebg
//    setBulletEffect         P1,GS_VeryLargeEnergyCannon,BulletCannonVeryLarge04.ebg
setBulletEffect         P1,GS_LargeEnergyCannon,BulletCannonLarge.ebg
    setBulletEffect         P1,GS_LargeEnergyCannon,BulletCannonLarge.ebg
    setBulletEffect         P1,GS_LargeEnergyCannon,BulletCannonLarge02.ebg
    setBulletEffect         P1,GS_LargeEnergyCannon,BulletCannonLarge03.ebg
//    setBulletEffect         P1,GS_LargeEnergyCannon,BulletCannonLarge04.ebg
setBulletEffect         P1,GS_MediumEnergyCannon,BulletCannonMed.ebg
    setBulletEffect         P1,GS_MediumEnergyCannon,BulletCannonMed.ebg
    setBulletEffect         P1,GS_MediumEnergyCannon,BulletCannonMed02.ebg
    setBulletEffect         P1,GS_MediumEnergyCannon,BulletCannonMed03.ebg
//    setBulletEffect         P1,GS_MediumEnergyCannon,BulletCannonMed04.ebg
setBulletEffect         P1,GS_SmallEnergyCannon,BulletGatling.ebg
    setBulletEffect         P1,GS_SmallEnergyCannon,BulletGatling.ebg
    setBulletEffect         P1,GS_SmallEnergyCannon,BulletGatling02.ebg
    setBulletEffect         P1,GS_SmallEnergyCannon,BulletGatling03.ebg
//    setBulletEffect         P1,GS_SmallEnergyCannon,BulletGatling04.ebg


setBulletEffect         P1,GS_MediumProjectile,BulletProjectile.ebg

setBulletColor         P1,GS_SmallPlasmaBomb,100,184,255
setBulletColor         P1,GS_MediumPlasmaBomb,100,184,255
setBulletColor         P1,GS_LargePlasmaBomb,100,184,255
setBulletColor         P1,GS_VeryLargePlasmaBomb,100,184,255

bigBoomFactor           P1,CLASS_Fighter, -10



