//
//***R2  Loads***
//
//B5 Explosion .ebg loads
LoadEffect              B5explosion.ebg
LoadEffect              B5sparks.ebg
LoadEffect              B5sparksLite.ebg
LoadEffect              B5fireball.ebg
LoadEffect	              B5genericdebris.ebg
LoadEffect	              B5TestExplosionLarge.ebg
LoadEffect	              B5TestExplosionMS.ebg
LoadEffect	              B5genericdebrisspawn.ebg
LoadEffect	              HitLargeCannon.ebg
//bullets
LoadEffect              BulletIonRay.ebg
LoadEffect              BulletMissiles.ebg
LoadEffect              BulletPlasmaBomb.ebg
LoadEffect              BulletEnergy.ebg

//specials
LoadEffect              TractorBeam.ebg

//fire effects
LoadEffect              FireGatling.ebg

//DestdamageSmall.ebg
LoadEffect              DDSfireball.ebg
LoadEffect              DDSsparks.ebg
LoadEffect              DDSshockwave.ebg
LoadEffect              DDSshockwave32.ebg
LoadEffect              DDSdebris.ebg

//DestDamageLarge.ebg
LoadEffect              DDLmultiFireball.ebg
LoadEffect              DDLsparks.ebg

//DestProjectileSmall.ebg
LoadEffect              DPSsmokePuff.ebg

//DestProjectileLarge.ebg
LoadEffect              DPLboom.ebg

//DestBeam.ebg
LoadEffect              DBsphere.ebg
LoadEffect              DBboom.ebg


//FireIonCannonVeryLarge.ebg
LoadEffect              FireIonCannonVeryLarge01.ebg
LoadEffect              FireIonCannonVeryLarge02.ebg
LoadEffect              FireIonCannonVeryLarge03.ebg

//FireIonCannonLarge.ebg
LoadEffect              FireIonCannonLarge01.ebg
LoadEffect              FireIonCannonLarge02.ebg
LoadEffect              FireIonCannonLarge03.ebg

//FireIonCannonMedium.ebg
LoadEffect              FireIonCannonMedium01.ebg
LoadEffect              FireIonCannonMedium02.ebg
LoadEffect              FireIonCannonMedium03.ebg

//FireIonCannonSmall.ebg
LoadEffect              FireIonCannonSmall01.ebg
LoadEffect              FireIonCannonSmall02.ebg
LoadEffect              FireIonCannonSmall03.ebg

//FireProjectileMedium.ebg
LoadEffect              FireProjectileMedium01.ebg
LoadEffect              FireProjectileMedium02.ebg
LoadEffect              FireProjectileMedium03.ebg

//FireEnergyVeryLarge.ebg
LoadEffect              FireEnergyVeryLarge01.ebg
LoadEffect              FireEnergyVeryLarge02.ebg
LoadEffect              FireEnergyVeryLarge03.ebg

//FireEnergyLarge.ebg
LoadEffect              FireEnergyLarge01.ebg
LoadEffect              FireEnergyLarge02.ebg
LoadEffect              FireEnergyLarge03.ebg

//FireEnergyMedium.ebg
LoadEffect              FireEnergyMedium01.ebg
LoadEffect              FireEnergyMedium02.ebg
LoadEffect              FireEnergyMedium03.ebg

//FireEnergySmall.ebg
LoadEffect              FireEnergySmall01.ebg
LoadEffect              FireEnergySmall02.ebg
LoadEffect              FireEnergySmall03.ebg

//FireEnergy.ebg
LoadEffect              FireEnergy01.ebg
LoadEffect              FireEnergy02.ebg
LoadEffect              FireEnergy03.ebg

//FireMines
LoadEffect              FireMines01.ebg
LoadEffect              FireMines02.ebg
LoadEffect              FireMines03.ebg

//FireMissiles
LoadEffect              FireMissiles.ebg
LoadEffect              FireMissiles01.ebg
LoadEffect              FireMissiles02.ebg
LoadEffect              FireMissiles03.ebg




//HitEnergy.ebg
LoadEffect              HitEnergy01.ebg
LoadEffect              HitEnergy02.ebg
LoadEffect              HitEnergy03.ebg

//HitProjectile.ebg
LoadEffect              HitProjectile01.ebg
LoadEffect              HitProjectile02.ebg
LoadEffect              HitProjectile03.ebg


//HitIonBeam
LoadEffect              IonBeamZap.ebg


//
//This section defines the basic set of event bindings
//damage,projectile,beam,collision,special are the death types.
//See objtypes.h for classes of weapons and ships.
//

//
//***R2***
//


//deaths

setDeathEvent           R2,CLASS_Fighter,damage,DestDamageSmall.ebg
setDeathEvent           R2,CLASS_Fighter,projectile,DestBeamFighter.ebg
setDeathEvent           R2,CLASS_Fighter,beam,destdamagefighter.ebg

setDeathEvent           R2,CLASS_Corvette,damage,DestDamageSmall.ebg
setDeathEvent           R2,CLASS_Corvette,projectile,DestDamageFighter.ebg
setDeathEvent           R2,CLASS_Corvette,beam,DestBeamFighter.ebg

setDeathEvent           R2,CLASS_Frigate,damage,B5TestExplosionLarge.ebg
setDeathEvent           R2,CLASS_Frigate,projectile,DestDamageLarge.ebg
setDeathEvent           R2,CLASS_Frigate,beam,DestDamageFighter.ebg

setDeathEvent           R2,CLASS_Destroyer,damage,B5TestExplosionLarge.ebg
setDeathEvent           R2,CLASS_Destroyer,projectile,DestDamageLarge.ebg
setDeathEvent           R2,CLASS_Destroyer,beam,DestDamageLarge.ebg

setDeathEvent           R2,CLASS_Carrier,damage,DestDamageLarge.ebg
setDeathEvent           R2,CLASS_Carrier,projectile,B5TestExplosionLarge.ebg
setDeathEvent           R2,CLASS_Carrier,beam,destdamagefighter.ebg

setDeathEvent           R2,CLASS_HeavyCruiser,damage,DestDamageLarge.ebg
setDeathEvent           R2,CLASS_HeavyCruiser,projectile,B5TestExplosionLarge.ebg
setDeathEvent           R2,CLASS_HeavyCruiser,beam,destdamagefighter.ebg

setDeathEvent           R2,CLASS_Mothership,damage,DestDamageMS.ebg
setDeathEvent           R2,CLASS_Mothership,projectile,DestDamageMS.ebg
setDeathEvent           R2,CLASS_Mothership,beam,DestDamageMS.ebg

setDeathEvent           R2,CLASS_Resource,damage,DestDamageLarge.ebg
setDeathEvent           R2,CLASS_Resource,projectile,B5TestExplosionLarge.ebg
setDeathEvent           R2,CLASS_Resource,beam,destdamagefighter.ebg

setDeathEvent           R2,CLASS_NonCombat,damage,DestDamageLarge.ebg
setDeathEvent           R2,CLASS_NonCombat,projectile,B5TestExplosionLarge.ebg
setDeathEvent           R2,CLASS_NonCombat,beam,destdamagefighter.ebg


//firing

setFireEvent            R2,GS_VeryLargeIonCannon,FireLaser.ebg
    setFireEvent            R2,GS_VeryLargeIonCannon,FireLaser.ebg
    setFireEvent            R2,GS_VeryLargeIonCannon,FireLaser01.ebg
    setFireEvent            R2,GS_VeryLargeIonCannon,FireLaser01.ebg
    setFireEvent            R2,GS_VeryLargeIonCannon,FireLaser01.ebg
setFireEvent            R2,GS_LargeIonCannon,FireDrakhBeam.ebg
    setFireEvent            R2,GS_LargeIonCannon,FireDrakhBeam.ebg
    setFireEvent            R2,GS_LargeIonCannon,FireDrakhBeam01.ebg
    setFireEvent            R2,GS_LargeIonCannon,FireDrakhBeam01.ebg
    setFireEvent            R2,GS_LargeIonCannon,FireDrakhBeam01.ebg
setFireEvent            R2,GS_MediumIonCannon,FireFusionBeam.ebg
    setFireEvent            R2,GS_MediumIonCannon,FireFusionBeam.ebg
    setFireEvent            R2,GS_MediumIonCannon,FireFusionBeam01.ebg
    setFireEvent            R2,GS_MediumIonCannon,FireFusionBeam01.ebg
    setFireEvent            R2,GS_MediumIonCannon,FireFusionBeam01.ebg
setFireEvent            R2,GS_SmallIonCannon,FireLightningBeam.ebg
    setFireEvent            R2,GS_SmallIonCannon,FireLightningBeam.ebg
    setFireEvent            R2,GS_SmallIonCannon,FireLightningBeam01.ebg
    setFireEvent            R2,GS_SmallIonCannon,FireLightningBeam01.ebg
    setFireEvent            R2,GS_SmallIonCannon,FireLightningBeam01.ebg

setFireEvent            R2,GS_Laser,FireSmallNeutronBeam.ebg
    setFireEvent            R2,GS_Laser,FireSmallNeutronBeam.ebg
    setFireEvent            R2,GS_Laser,FireSmallNeutronBeam01.ebg
    setFireEvent            R2,GS_Laser,FireSmallNeutronBeam01.ebg
    setFireEvent            R2,GS_Laser,FireSmallNeutronBeam01.ebg

setHitEvent             R2,GS_MediumProjectile,HitMediumCannon.ebg
    setHitEvent             R2,GS_MediumProjectile,HitMediumCannon.ebg
    setHitEvent             R2,GS_MediumProjectile,HitMediumCannon.ebg
    setHitEvent             R2,GS_MediumProjectile,HitMediumCannon.ebg

setHitEvent             R2,GS_SmallProjectile,HitMediumCannon.ebg
    setHitEvent             R2,GS_SmallProjectile,HitMediumCannon.ebg
    setHitEvent             R2,GS_SmallProjectile,HitMediumCannon.ebg
    setHitEvent             R2,GS_SmallProjectile,HitMediumCannon.ebg

setFireEvent            R2,GS_VeryLargeEnergyCannon,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_VeryLargeEnergyCannon,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_VeryLargeEnergyCannon,FireLargePulseWhite01.ebg
    setFireEvent            R2,GS_VeryLargeEnergyCannon,FireLargePulseWhite01.ebg
    setFireEvent            R2,GS_VeryLargeEnergyCannon,FireLargePulseWhite01.ebg
setFireEvent            R2,GS_LargeEnergyCannon,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_LargeEnergyCannon,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_LargeEnergyCannon,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_LargeEnergyCannon,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_LargeEnergyCannon,FireLargePulseWhite.ebg
setFireEvent            R2,GS_MediumEnergyCannon,FireSmallPulseWhite.ebg
    setFireEvent            R2,GS_MediumEnergyCannon,FireSmallPulseWhite.ebg
    setFireEvent            R2,GS_MediumEnergyCannon,FireSmallPulseWhite01.ebg
    setFireEvent            R2,GS_MediumEnergyCannon,FireSmallPulseWhite01.ebg
    setFireEvent            R2,GS_MediumEnergyCannon,FireSmallPulseWhite01.ebg
setFireEvent            R2,GS_SmallEnergyCannon,FireSmallPulseWhite.ebg
    setFireEvent            R2,GS_SmallEnergyCannon,FireSmallPulseWhite.ebg
    setFireEvent            R2,GS_SmallEnergyCannon,FireSmallPulseWhite01.ebg
    setFireEvent            R2,GS_SmallEnergyCannon,FireSmallPulseWhite01.ebg
    setFireEvent            R2,GS_SmallEnergyCannon,FireSmallPulseWhite01.ebg

setFireEvent            R2,GS_MineLauncher,FireMines.ebg
    setFireEvent            R2,GS_MineLauncher,FireMines.ebg
    setFireEvent            R2,GS_MineLauncher,FireMines.ebg
    setFireEvent            R2,GS_MineLauncher,FireMines.ebg
setFireEvent            R2,GS_MissleLauncher,FireMissiles.ebg
    setFireEvent            R2,GS_MissleLauncher,FireMissiles.ebg
    setFireEvent            R2,GS_MissleLauncher,FireMissiles.ebg
    setFireEvent            R2,GS_MissleLauncher,FireMissiles.ebg

setFireEvent            R2,GS_VeryLargePlasmaBomb,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_VeryLargePlasmaBomb,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_VeryLargePlasmaBomb,FireLargePulseWhite01.ebg
    setFireEvent            R2,GS_VeryLargePlasmaBomb,FireLargePulseWhite01.ebg
    setFireEvent            R2,GS_VeryLargePlasmaBomb,FireLargePulseWhite01.ebg
setFireEvent            R2,GS_LargePlasmaBomb,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_LargePlasmaBomb,FireLargePulseWhite.ebg
    setFireEvent            R2,GS_LargePlasmaBomb,FireLargePulseWhite01.ebg
    setFireEvent            R2,GS_LargePlasmaBomb,FireLargePulseWhite01.ebg
    setFireEvent            R2,GS_LargePlasmaBomb,FireLargePulseWhite01.ebg
setFireEvent            R2,GS_MediumPlasmaBomb,FirePlasmaMedium.ebg
    setFireEvent            R2,GS_MediumPlasmaBomb,FirePlasmaMedium.ebg
    setFireEvent            R2,GS_MediumPlasmaBomb,FirePlasmaMedium.ebg
    setFireEvent            R2,GS_MediumPlasmaBomb,FirePlasmaMedium.ebg
    setFireEvent            R2,GS_MediumPlasmaBomb,FirePlasmaMedium.ebg
setFireEvent            R2,GS_SmallPlasmaBomb,FirePlasmaSmall.ebg
    setFireEvent            R2,GS_SmallPlasmaBomb,FirePlasmaSmall.ebg
    setFireEvent            R2,GS_SmallPlasmaBomb,FirePlasmaSmall.ebg
    setFireEvent            R2,GS_SmallPlasmaBomb,FirePlasmaSmall.ebg
    setFireEvent            R2,GS_SmallPlasmaBomb,FirePlasmaSmall.ebg


//hits

setHitEvent             R2,GS_VeryLargeIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_VeryLargeIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_VeryLargeIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_VeryLargeIonCannon,HitLargeBeam.ebg
setHitEvent             R2,GS_LargeIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_LargeIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_LargeIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_LargeIonCannon,HitLargeBeam.ebg
setHitEvent             R2,GS_MediumIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_MediumIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_MediumIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_MediumIonCannon,HitLargeBeam.ebg
setHitEvent             R2,GS_SmallIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_SmallIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_SmallIonCannon,HitLargeBeam.ebg
    setHitEvent             R2,GS_SmallIonCannon,HitLargeBeam.ebg

setHitEvent             R2,GS_Laser,HitSmallBeam.ebg
    setHitEvent             R2,GS_Laser,HitSmallBeam.ebg
    setHitEvent             R2,GS_Laser,HitSmallBeam.ebg
    setHitEvent             R2,GS_Laser,HitSmallBeam.ebg
setHitEvent             R2,GS_MediumProjectile,HitDrakhBeam.ebg
    setHitEvent             R2,GS_MediumProjectile,HitDrakhBeam.ebg
    setHitEvent             R2,GS_MediumProjectile,HitDrakhBeam.ebg
    setHitEvent             R2,GS_MediumProjectile,HitDrakhBeam.ebg

setHitEvent             R2,GS_SmallProjectile,HitCannon.ebg
    setHitEvent             R2,GS_SmallProjectile,HitCannon.ebg
    setHitEvent             R2,GS_SmallProjectile,HitCannon.ebg
    setHitEvent             R2,GS_SmallProjectile,HitCannon.ebg

setHitEvent             R2,GS_VeryLargeEnergyCannon,HitLargeCannon.ebg
    setHitEvent             R2,GS_VeryLargeEnergyCannon,HitLargeCannon.ebg
    setHitEvent             R2,GS_VeryLargeEnergyCannon,HitLargeCannon.ebg
    setHitEvent             R2,GS_VeryLargeEnergyCannon,HitLargeCannon.ebg
setHitEvent             R2,GS_LargeEnergyCannon,HitSmallCannon.ebg
    setHitEvent             R2,GS_LargeEnergyCannon,HitSmallCannon.ebg
    setHitEvent             R2,GS_LargeEnergyCannon,HitSmallCannon.ebg
    setHitEvent             R2,GS_LargeEnergyCannon,HitSmallCannon.ebg
setHitEvent             R2,GS_MediumEnergyCannon,HitSmallCannon.ebg
    setHitEvent             R2,GS_MediumEnergyCannon,HitSmallCannon.ebg
    setHitEvent             R2,GS_MediumEnergyCannon,HitSmallCannon.ebg
    setHitEvent             R2,GS_MediumEnergyCannon,HitSmallCannon.ebg
setHitEvent             R2,GS_SmallEnergyCannon,HitMediumCannon.ebg
    setHitEvent             R2,GS_SmallEnergyCannon,HitMediumCannon.ebg
    setHitEvent             R2,GS_SmallEnergyCannon,HitMediumCannon.ebg
    setHitEvent             R2,GS_SmallEnergyCannon,HitMediumCannon.ebg

setHitEvent             R2,GS_MineLauncher,HitExplosive.ebg
    setHitEvent             R2,GS_MineLauncher,HitExplosive.ebg
    setHitEvent             R2,GS_MineLauncher,HitExplosive.ebg
    setHitEvent             R2,GS_MineLauncher,HitExplosive.ebg
    setHitEvent             R2,GS_MineLauncher,HitExplosive.ebg
    setHitEvent             R2,GS_MineLauncher,HitExplosive.ebg
setHitEvent             R2,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             R2,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             R2,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             R2,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             R2,GS_MissleLauncher,HitLargeMissile.ebg
    setHitEvent             R2,GS_MissleLauncher,HitLargeMissile.ebg

setHitEvent             R2,GS_VeryLargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_VeryLargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_VeryLargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_VeryLargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_VeryLargePlasmaBomb,HitPlasma.ebg
setHitEvent             R2,GS_LargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_LargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_LargePlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_LargePlasmaBomb,HitPlasma.ebg
setHitEvent             R2,GS_MediumPlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_MediumPlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_MediumPlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_MediumPlasmaBomb,HitPlasma.ebg
setHitEvent             R2,GS_SmallPlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_SmallPlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_SmallPlasmaBomb,HitPlasma.ebg
    setHitEvent             R2,GS_SmallPlasmaBomb,HitPlasma.ebg



//Bullets

setBulletEffect         R2,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_SmallPlasmaBomb,BulletPlasmaBomb.ebg
setBulletEffect         R2,GS_MediumPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_MediumPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_MediumPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_MediumPlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_MediumPlasmaBomb,BulletPlasmaBomb.ebg
setBulletEffect         R2,GS_LargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_LargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_LargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_LargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_LargePlasmaBomb,BulletPlasmaBomb.ebg
setBulletEffect         R2,GS_VeryLargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_VeryLargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_VeryLargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_VeryLargePlasmaBomb,BulletPlasmaBomb.ebg
    setBulletEffect         R2,GS_VeryLargePlasmaBomb,BulletPlasmaBomb.ebg

setBulletEffect         R2,GS_VeryLargeIonCannon,BulletLaser.ebg
    setBulletEffect         R2,GS_VeryLargeIonCannon,BulletLaser.ebg
    setBulletEffect         R2,GS_VeryLargeIonCannon,BulletLaser.ebg
    setBulletEffect         R2,GS_VeryLargeIonCannon,BulletLaser.ebg
setBulletEffect         R2,GS_LargeIonCannon,bulletionray.ebg
    setBulletEffect         R2,GS_LargeIonCannon,bulletionray.ebg
    setBulletEffect         R2,GS_LargeIonCannon,bulletionray.ebg
    setBulletEffect         R2,GS_LargeIonCannon,bulletionray.ebg
setBulletEffect         R2,GS_MediumIonCannon,BulletFusionBeam.ebg
    setBulletEffect         R2,GS_MediumIonCannon,BulletFusionBeam.ebg
    setBulletEffect         R2,GS_MediumIonCannon,BulletFusionBeam.ebg
    setBulletEffect         R2,GS_MediumIonCannon,BulletFusionBeam.ebg
setBulletEffect         R2,GS_SmallIonCannon,BulletLightningBeam.ebg
    setBulletEffect         R2,GS_SmallIonCannon,BulletLightningBeam.ebg
    setBulletEffect         R2,GS_SmallIonCannon,BulletLightningBeam.ebg
    setBulletEffect         R2,GS_SmallIonCannon,BulletLightningBeam.ebg


setBulletEffect         R2,GS_Laser,BulletSmallNeutronBeam.ebg
    setBulletEffect         R2,GS_Laser,BulletSmallNeutronBeam.ebg
    setBulletEffect         R2,GS_Laser,BulletSmallNeutronBeam.ebg
    setBulletEffect         R2,GS_Laser,BulletSmallNeutronBeam.ebg


setBulletEffect         R2,GS_VeryLargeEnergyCannon,BulletLargePulseWhite.ebg
    setBulletEffect         R2,GS_VeryLargeEnergyCannon,BulletLargePulseWhite.ebg
    setBulletEffect         R2,GS_VeryLargeEnergyCannon,BulletLargePulseWhite02.ebg
    setBulletEffect         R2,GS_VeryLargeEnergyCannon,BulletLargePulseWhite02.ebg
    setBulletEffect         R2,GS_VeryLargeEnergyCannon,BulletLargePulseWhite02.ebg
setBulletEffect         R2,GS_LargeEnergyCannon,BulletMediumPulseWhite.ebg
    setBulletEffect         R2,GS_LargeEnergyCannon,BulletMediumPulseWhite.ebg
    setBulletEffect         R2,GS_LargeEnergyCannon,BulletMediumPulseWhite02.ebg
    setBulletEffect         R2,GS_LargeEnergyCannon,BulletMediumPulseWhite02.ebg
    setBulletEffect         R2,GS_LargeEnergyCannon,BulletMediumPulseWhite02.ebg
setBulletEffect         R2,GS_MediumEnergyCannon,BulletSmallPulseWhite.ebg
    setBulletEffect         R2,GS_MediumEnergyCannon,BulletSmallPulseWhite.ebg
    setBulletEffect         R2,GS_MediumEnergyCannon,BulletSmallPulseWhite02.ebg
    setBulletEffect         R2,GS_MediumEnergyCannon,BulletSmallPulseWhite02.ebg
    setBulletEffect         R2,GS_MediumEnergyCannon,BulletSmallPulseWhite02.ebg
setBulletEffect         R2,GS_SmallEnergyCannon,BulletSmallPulseWhite.ebg
    setBulletEffect         R2,GS_SmallEnergyCannon,BulletSmallPulseWhite.ebg
    setBulletEffect         R2,GS_SmallEnergyCannon,BulletSmallPulseWhite02.ebg
    setBulletEffect         R2,GS_SmallEnergyCannon,BulletSmallPulseWhite02.ebg
    setBulletEffect         R2,GS_SmallEnergyCannon,BulletSmallPulseWhite02.ebg

setBulletEffect         R2,GS_MediumProjectile,BulletDrakhBeam.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletDrakhBeam.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletDrakhBeam.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletDrakhBeam.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletDrakhBeam.ebg

setBulletEffect         R2,GS_MediumProjectile,BulletSmallPulseWhite.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletSmallPulseWhite.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletSmallPulseWhite02.ebg
    setBulletEffect         R2,GS_MediumProjectile,BulletSmallPulseWhite02.ebg


setBulletColor         R2,GS_MediumProjectile,200,150,20

setBulletColor         R2,GS_SmallPlasmaBomb,116,212,27
setBulletColor         R2,GS_MediumPlasmaBomb,256,84,29
setBulletColor         R2,GS_LargePlasmaBomb,30,217,230
setBulletColor         R2,GS_VeryLargePlasmaBomb,199,205,144

setBulletColor         R2,GS_VeryLargeIonCannon,251,22,0 
setBulletColor         R2,GS_LargeIonCannon,230,238,83
setBulletColor         R2,GS_MediumIonCannon,176,115,173
setBulletColor         R2,GS_SmallIonCannon,252,252,208

setBulletColor         R2,GS_Laser,230,238,83

setAsteroidEffect      R2,resource_solid.ebg
        setAsteroidEffect      R2,resource_solid.ebg
        setAsteroidEffect      R2,resource_solid.ebg
        setAsteroidEffect      R2,resource_solid.ebg

//setGaseousEffect      R2,resource_solid.ebg
  setGaseousEffect      R2,resource_gaseous.ebg
        setGaseousEffect      R2,resource_gaseous.ebg
        setGaseousEffect      R2,resource_gaseous.ebg
        setGaseousEffect      R2,resource_gaseous.ebg

//setTractorBeamEffect    R2,TractorBeam.ebg
setTractorBeamEffect    R2,salvage.ebg
        setTractorBeamEffect    R2,salvage.ebg
        setTractorBeamEffect    R2,salvage.ebg
        setTractorBeamEffect    R2,salvage.ebg

//laser beam (defense fighter) destroys bullet
//setBulletDestroyEvent            R2,GS_MediumProjectile,LaserDestBulletCannon.ebg
setBulletDestroyEvent            R2,GS_MediumProjectile,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumProjectile,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumProjectile,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumProjectile,deflect.ebg
setBulletDestroyEvent            R2,GS_SmallProjectile,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallProjectile,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallProjectile,deflect.ebg

setBulletDestroyEvent            R2,GS_VeryLargeEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargeEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargeEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargeEnergyCannon,deflect.ebg
setBulletDestroyEvent            R2,GS_LargeEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_LargeEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_LargeEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_LargeEnergyCannon,deflect.ebg
setBulletDestroyEvent            R2,GS_MediumEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumEnergyCannon,deflect.ebg
setBulletDestroyEvent            R2,GS_SmallEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallEnergyCannon,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallEnergyCannon,deflect.ebg

setBulletDestroyEvent            R2,GS_MediumPlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumPlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumPlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_MediumPlasmaBomb,deflect.ebg
setBulletDestroyEvent            R2,GS_VeryLargePlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargePlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargePlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargePlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_VeryLargePlasmaBomb,deflect.ebg
setBulletDestroyEvent            R2,GS_SmallPlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallPlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallPlasmaBomb,deflect.ebg
    setBulletDestroyEvent            R2,GS_SmallPlasmaBomb,deflect.ebg

bigBoomFactor           R2,CLASS_Fighter, -10

